[nltk_data] Downloading package stopwords to
[nltk_data]     /home/aleatoryfreak/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
Not Found: /
Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/aleatoryfreak/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
Bad Request: /
Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/aleatoryfreak/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
Bad Request: /
Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /
Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/aleatoryfreak/resumate/venv/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.177.226.93'. You may need to add '172.177.226.93' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
